name: Deploy to GitHub Pages

on:
  workflow_dispatch: {}
  push:
    branches: ["develop"]

permissions:
  id-token: write
  contents: read
  pages: write

concurrency:
  cancel-in-progress: false
  group: "pages"

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Export to Web
        uses: firebelley/godot-export@v5.2.1
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'builds/web/.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
